# Makefile for background images
# Diego Martínez Castañeda <dmartinez@solutia-it.es>
# mar dic 27 13:16:18 CET 2016

install:
	#cp -f gecos_bg.jpg /usr/share/images/desktop-base
	install \
		--owner=root \
		--group=root \
		--mode=644 \
		--target-directory=/usr/share/images/desktop-base \
		gecos_bg.jpg \

